services:
  db:
    image: postgres:17.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_NAME: ${DB_NAMEDB}
      POSTGRES_USERNAME: ${DB_USERNAME}
    container_name: shopTest
    volumes:
      - ./postgres:/var/lib/postgresql/data